# Developer note:
#
# Run `make` or `make help` to display a list of targets and help texts.
#
# If you add a new command, add a help text by adding a comment on the same
# line as the target name. You should use the following structure:
# `<target name>:  ## <help text>`
.PHONY: help
.DEFAULT_GOAL := help
help:
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage: make \033[36m<target>\033[0m\n\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-10s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

# Makefile
new: ## Creates a new module - `make new MODULE=module-name`
	@cp -r src/templates/module modules/${MODULE}
	@cp src/templates/module.mk modules/${MODULE}/Makefile

new-blank: ## Creates a new module - `make new MODULE=module-name`
	@mkdir -p modules/${MODULE}/{docs,templates,test}
	@touch modules/${MODULE}/{main,providers,outputs,variables}.tofu
	@echo "# ${MODULE}" >> modules/${MODULE}/README.md
	@git checkout -b feat/${MODULE}
	@cd modules/${MODULE}
	@git commit -m "Added template for '${MODULE}' generated by Makefile"

terraform-tools-install: ## Installs tools that this repository uses
	@brew install terraform-docs infracost

terraform-generate-docs: ## Outputs the command for generating documentation
	@echo "terraform-docs markdown table --output-file README.md ."

terraform-format: ## Formats the repository according to Hashicorp's format standards
	tofu fmt -recursive

##@ Pre-commit Hooks

pre-commit-install: ## Installs pre-commit tool (supports pacman, pipx, and pip)
	@if command -v pre-commit >/dev/null 2>&1; then \
		echo "pre-commit is already installed (version: $$(pre-commit --version))"; \
	elif command -v pacman >/dev/null 2>&1; then \
		echo "Detected Arch Linux - installing pre-commit via pacman..."; \
		sudo pacman -S --noconfirm pre-commit; \
	elif command -v pipx >/dev/null 2>&1; then \
		echo "Installing pre-commit via pipx..."; \
		pipx install pre-commit; \
	elif command -v pip3 >/dev/null 2>&1; then \
		echo "Installing pre-commit via pip3..."; \
		pip3 install --user pre-commit; \
	elif command -v pip >/dev/null 2>&1; then \
		echo "Installing pre-commit via pip..."; \
		pip install --user pre-commit; \
	else \
		echo "Error: No suitable package manager found."; \
		echo "Please install one of: pacman (Arch), pipx, or pip"; \
		exit 1; \
	fi
	@echo "Pre-commit installed successfully!"

pre-commit-setup: pre-commit-install ## Installs pre-commit tool and sets up git hooks
	pre-commit install
	pre-commit install --hook-type commit-msg
	echo "Git hooks installed successfully!"
	echo "Run 'make pre-commit-run' to test the hooks on all files"

pre-commit-run: ## Runs pre-commit hooks on all files
	pre-commit run --all-files

pre-commit-update: ## Updates pre-commit hooks to latest versions
	pre-commit autoupdate

setup-dev: pre-commit-setup ## Sets up local development environment (installs pre-commit hooks)
	echo "Development environment setup complete!"
